### ISSUE TITLE
add command to pretty print

### ISSUE THREAD

**Issue by adrienlacombe** [LedgerHQ/clear-signing-erc7730-registry#77]
this is to keep formatting consistent

**Comment by jnicoulaud-ledger** [comment]
Done in https://github.com/LedgerHQ/python-erc7730/pull/147, see usage doc [here](https://ledgerhq.github.io/python-erc7730/pages/usage_cli.html#erc7730-format)
The registry also has a daily job to reformat all files, [example PR](https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/92)

**Comment by adrienlacombe** [comment]
merci @jnicoulaud-ledger :)
